[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "aiogram>=3.19.0",
    "aiohttp>=3.11.14",
    "aiosqlite>=0.21.0",
    "apscheduler>=3.11.0",
    "yandex-gpt>=0.3.0",
]
